<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-01-19T06:26:16+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Kongpong',
        ],
    ],
];
